config/routes.rb
Rebirth::Application.routes.draw do
  resources :journals

  resources :categories

  resources :elements

  resources :accounts

  resources :transactions

  resources :transaction_methods

  resources :contacts

  root :to => 'home#index'

end

app/models/element.rb
class Element < ActiveRecord::Base
  has_many :categories
end

app/controllers/elements_controller.rb
class ElementsController < ApplicationController
  # GET /elements
  # GET /elements.json
  def index
    @elements = Element.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @elements }
    end
  end

  # GET /elements/1
  # GET /elements/1.json
  def show
    @element = Element.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @element }
    end
  end

  # GET /elements/new
  # GET /elements/new.json
  def new
    @element = Element.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @element }
    end
  end

  # GET /elements/1/edit
  def edit
    @element = Element.find(params[:id])
  end

  # POST /elements
  # POST /elements.json
  def create
    @element = Element.new(params[:element])

    respond_to do |format|
      if @element.save
        format.html { redirect_to @element, notice: 'Element was successfully created.' }
        format.json { render json: @element, status: :created, location: @element }
      else
        format.html { render action: "new" }
        format.json { render json: @element.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /elements/1
  # PUT /elements/1.json
  def update
    @element = Element.find(params[:id])

    respond_to do |format|
      if @element.update_attributes(params[:element])
        format.html { redirect_to @element, notice: 'Element was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @element.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /elements/1
  # DELETE /elements/1.json
  def destroy
    @element = Element.find(params[:id])
    @element.destroy

    respond_to do |format|
      format.html { redirect_to elements_url }
      format.json { head :ok }
    end
  end
end

app/helpers/elements_helper.rb
module ElementsHelper
end

app/views/elements/_form.html.erb
<%= form_for(@element) do |f| %>
  <% if @element.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@element.errors.count, "error") %> prohibited this element from being saved:</h2>

      <ul>
      <% @element.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :caption %><br />
    <%= f.text_field :caption %>
  </div>
  <div class="field">
    <%= f.label :invert %><br />
    <%= f.number_field :invert %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/elements/edit.html.erb
<h1>Editing element</h1>

<%= render 'form' %>

<%= link_to 'Show', @element %> |
<%= link_to 'Back', elements_path %>

app/views/elements/index.html.erb
<h1>Listing elements</h1>

<table>
  <tr>
    <th>Caption</th>
    <th>Invert</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @elements.each do |element| %>
  <tr>
    <td><%= element.caption %></td>
    <td><%= element.invert %></td>
    <td><%= link_to 'Show', element %></td>
    <td><%= link_to 'Edit', edit_element_path(element) %></td>
    <td><%= link_to 'Destroy', element, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Element', new_element_path %>

app/views/elements/new.html.erb
<h1>New element</h1>

<%= render 'form' %>

<%= link_to 'Back', elements_path %>

app/views/elements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Caption:</b>
  <%= @element.caption %>
</p>

<p>
  <b>Invert:</b>
  <%= @element.invert %>
</p>


<%= link_to 'Edit', edit_element_path(@element) %> |
<%= link_to 'Back', elements_path %>