config/routes.rb
Rebirth::Application.routes.draw do
  resources :journals

  resources :categories

  resources :elements

  resources :accounts

  resources :transactions

  resources :transaction_methods

  resources :contacts

  root :to => 'home#index'

end

app/models/journal.rb
class Journal < ActiveRecord::Base
  belongs_to :transaction
  belongs_to :account
end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController
  # GET /journals
  # GET /journals.json
  def index
    @journals = Journal.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @journals }
    end
  end

  # GET /journals/1
  # GET /journals/1.json
  def show
    @journal = Journal.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @journal }
    end
  end

  # GET /journals/new
  # GET /journals/new.json
  def new
    @journal = Journal.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @journal }
    end
  end

  # GET /journals/1/edit
  def edit
    @journal = Journal.find(params[:id])
  end

  # POST /journals
  # POST /journals.json
  def create
    @journal = Journal.new(params[:journal])

    respond_to do |format|
      if @journal.save
        format.html { redirect_to @journal, notice: 'Journal was successfully created.' }
        format.json { render json: @journal, status: :created, location: @journal }
      else
        format.html { render action: "new" }
        format.json { render json: @journal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /journals/1
  # PUT /journals/1.json
  def update
    @journal = Journal.find(params[:id])

    respond_to do |format|
      if @journal.update_attributes(params[:journal])
        format.html { redirect_to @journal, notice: 'Journal was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @journal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /journals/1
  # DELETE /journals/1.json
  def destroy
    @journal = Journal.find(params[:id])
    @journal.destroy

    respond_to do |format|
      format.html { redirect_to journals_url }
      format.json { head :ok }
    end
  end
end

app/helpers/journals_helper.rb
module JournalsHelper
end

app/views/journals/_form.html.erb
<%= form_for(@journal) do |f| %>
  <% if @journal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@journal.errors.count, "error") %> prohibited this journal from being saved:</h2>

      <ul>
      <% @journal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :transaction_id %><br />
    <%= f.text_field :transaction_id %>
  </div>
  <div class="field">
    <%= f.label :account_id %><br />
    <%= collection_select :journal, :account_id, Account.find(:all), :id, :caption %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :memo %><br />
    <%= f.text_field :memo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/journals/edit.html.erb
<h1>Editing journal</h1>

<%= render 'form' %>

<%= link_to 'Show', @journal %> |
<%= link_to 'Back', journals_path %>

app/views/journals/index.html.erb
<h1>Listing journals</h1>

<table>
  <tr>
    <th>Amount</th>
    <th>Date</th>
    <th>Memo</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @journals.each do |journal| %>
  <tr>
    <td><%= journal.amount %></td>
    <td><%= journal.date %></td>
    <td><%= journal.memo %></td>
    <td><%= link_to 'Show', journal %></td>
    <td><%= link_to 'Edit', edit_journal_path(journal) %></td>
    <td><%= link_to 'Destroy', journal, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Journal', new_journal_path %>

app/views/journals/new.html.erb
<h1>New journal</h1>

<%= render 'form' %>

<%= link_to 'Back', journals_path %>

app/views/journals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Amount:</b>
  <%= @journal.amount %>
</p>

<p>
  <b>Date:</b>
  <%= @journal.date %>
</p>

<p>
  <b>Memo:</b>
  <%= @journal.memo %>
</p>


<%= link_to 'Edit', edit_journal_path(@journal) %> |
<%= link_to 'Back', journals_path %>